// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyBlazorApp.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyBlazorApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251215090756_AddMoreProductsWithImages")]
    partial class AddMoreProductsWithImages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyBlazorApp.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminPasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AdminUserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdminPasswordHash = "AQAAAAIAAYagAAAAEKw4201BnMtft9Iz+/LKObjQQtYQfKzEAmGsCa/OTkcQsZVTFv3XR4hACZ2Rtei9Og==",
                            AdminUserName = "TechAdmin1"
                        },
                        new
                        {
                            Id = 2,
                            AdminPasswordHash = "AQAAAAIAAYagAAAAEHyQVL2GA9mtR7BideC77KIazRdMhPpNYdYREjHm8sPn1ua0oZb7WcZp9RF4JuYk9w==",
                            AdminUserName = "TechAdmin2"
                        });
                });

            modelBuilder.Entity("MyBlazorApp.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "AQAAAAIAAYagAAAAENrC26B5B3NUJz1gHkP/L71m+TmRydBEBYpOCST+NypUHYejCsZc/f2nTB+lnGRCKg==",
                            Username = "client1"
                        },
                        new
                        {
                            Id = 2,
                            PasswordHash = "AQAAAAIAAYagAAAAEFEXGCpv9CkS5/MUG3ltvJ6rss2+59AhrPgo+ekuUbJiASWTpOdVEal8HdX6lh5kKg==",
                            Username = "client2"
                        });
                });

            modelBuilder.Entity("MyBlazorApp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageFile")
                        .HasColumnType("text");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductStock")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageFile = "",
                            ProductName = "Asus Vivobook X1605VA-OLED-SH2182W Laptop 16 Core i7 13620H/16 GB/1 TB/UHD Graphics/Windows 11 Home",
                            ProductPrice = 699m,
                            ProductStock = 10
                        },
                        new
                        {
                            Id = 2,
                            ImageFile = "",
                            ProductName = "Dell Alienware Aurora 16 Laptop 16 WQXGA Core 7 240H/32 GB/1 TB/RTX 5060 8 GB/Windows 11 Home",
                            ProductPrice = 1299m,
                            ProductStock = 5
                        },
                        new
                        {
                            Id = 3,
                            ImageFile = "/images/products/mac1.png",
                            ProductName = "Apple MacBook Air 13 M4 8-Core/16GB/256GB/10-Core GPU Midnight Laptop",
                            ProductPrice = 1149m,
                            ProductStock = 20
                        },
                        new
                        {
                            Id = 4,
                            ImageFile = "/images/products/mac2.png",
                            ProductName = "Apple MacBook Pro 16 M4 Max 16-Core/48GB/1TB/40-Core GPU Silver Laptop",
                            ProductPrice = 4839m,
                            ProductStock = 10
                        },
                        new
                        {
                            Id = 5,
                            ImageFile = "/images/products/dell.png",
                            ProductName = "Dell XPS 9640 U7-155H/32GB/1TB/W11P RTX 4060 8GB Laptop",
                            ProductPrice = 2699m,
                            ProductStock = 30
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
