// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyBlazorApp.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyBlazorApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251214093501_AddCustomerTable")]
    partial class AddCustomerTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyBlazorApp.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminPasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AdminUserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdminPasswordHash = "AQAAAAIAAYagAAAAEKw4201BnMtft9Iz+/LKObjQQtYQfKzEAmGsCa/OTkcQsZVTFv3XR4hACZ2Rtei9Og==",
                            AdminUserName = "TechAdmin1"
                        },
                        new
                        {
                            Id = 2,
                            AdminPasswordHash = "AQAAAAIAAYagAAAAEHyQVL2GA9mtR7BideC77KIazRdMhPpNYdYREjHm8sPn1ua0oZb7WcZp9RF4JuYk9w==",
                            AdminUserName = "TechAdmin2"
                        });
                });

            modelBuilder.Entity("MyBlazorApp.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "AQAAAAEAACcQAAAAEKA4StxvHKZ/9HZVU7U8nYaohjj8gHWpsqeH2pGwmDFP9LnM/+yHwVEgvqj/fq5YJw==",
                            Username = "client1"
                        },
                        new
                        {
                            Id = 2,
                            PasswordHash = "AQAAAAEAACcQAAAAEHpA5i4C3mUbvDSppzhDVYPspdZT6v/Aocilx89V2YIcZH1eArCNxxCU/y7fbjBugg==",
                            Username = "client2"
                        });
                });

            modelBuilder.Entity("MyBlazorApp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageFile")
                        .HasColumnType("text");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductStock")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageFile = "",
                            ProductName = "Asus Vivobook X1605VA-OLED-SH2182W Laptop 16 Core i7 13620H/16 GB/1 TB/UHD Graphics/Windows 11 Home",
                            ProductPrice = 699m,
                            ProductStock = 10
                        },
                        new
                        {
                            Id = 2,
                            ImageFile = "",
                            ProductName = "Dell Alienware Aurora 16 Laptop 16 WQXGA Core 7 240H/32 GB/1 TB/RTX 5060 8 GB/Windows 11 Home",
                            ProductPrice = 1299m,
                            ProductStock = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
